version: '3'

services:
  redis:
    image: 'redis:5.0.3'
    command: redis-server

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "airflow" ]
      interval: 5s
      retries: 5
    restart: always

  webserver:
    # image: airflow:latest
    restart: always
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - AWS_REGION=ap-southeast-2
      - AWS_DEFAULT_REGION=ap-southeast-2
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_BASE_URL=http://localhost:8080
      - ENABLE_REMOTE_LOGGING=False
      - STAGE=dev
      - AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL=15
    volumes:
      - ./app/dags:/usr/local/airflow/data/dags
      - ./app/plugins:/usr/local/airflow/data/plugins
      - ~/.aws:/usr/local/airflow/.aws
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    # image: airflow:latest
    build: .
    restart: always
    depends_on:
      - redis
      - webserver
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - STAGE=dev
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    # image: airflow:latest
    build: .
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./app/dags:/usr/local/airflow/data/dags
      - ./app/plugins:/usr/local/airflow/data/plugins
      - ~/.aws:/usr/local/airflow/.aws
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_BASE_URL=http://localhost:8080
      - ENABLE_REMOTE_LOGGING=False
      - STAGE=dev
    command: scheduler

  worker:
    # image: airflow:latest
    build: .
    restart: always
    depends_on:
      - webserver
      - scheduler
    volumes:
      - ./app/dags:/usr/local/airflow/dags
      - ./app/plugins:/usr/local/airflow/data/plugins
      - ~/.aws:/usr/local/airflow/.aws
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_BASE_URL=http://localhost:8080
      - ENABLE_REMOTE_LOGGING=False
      - STAGE=dev
    command: worker

  #  worker2:
  #    image: airflow:latest
  #    restart: always
  #    depends_on:
  #      - webserver
  #      - scheduler
  #    volumes:
  #      - ./dags:/usr/local/airflow/dags
  #    environment:
  #      - REDIS_HOST=redis
  #      - REDIS_PORT=6379
  #      - POSTGRES_HOST=postgres
  #      - POSTGRES_PORT=5432
  #      - POSTGRES_USER=airflow
  #      - POSTGRES_PASSWORD=airflow
  #      - POSTGRES_DB=airflow
  #      - FERNET_KEY=${AIRFLOW_FERNET_KEY}
  #      - AIRFLOW_BASE_URL=http://localhost:8080
  #      - ENABLE_REMOTE_LOGGING=False
  #      - STAGE=dev
  #    command: worker
  triggerer:
    restart: always
    build: .
    depends_on:
      - webserver
      - scheduler
      - worker
    volumes:
      - ./app/dags:/usr/local/airflow/data/dags
      - ./app/plugins:/usr/local/airflow/data/plugins
      - ~/.aws:/usr/local/airflow/.aws
    environment:
      - REDIS_HOST=redis
      - AWS_DEFAULT_REGION=ap-southeast-2
      - AIRFLOW_VAR_AWS_REGION=ap-southeast-2
      - AWS_REGION=ap-southeast-2
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
      - FERNET_KEY=${AIRFLOW_FERNET_KEY}
      - AIRFLOW_BASE_URL=http://localhost:8080
      - ENABLE_REMOTE_LOGGING=False
      - STAGE=dev
    command: triggerer
